name: Build Repository
on:
  push:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: "temurin"
      - name: Build
        run: ./gradlew clean build